eureka:
  client:
    register-with-eureka: false
server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://users:8080
          predicates:
            - Path=/api/v1/users/**

management:
  tracing:
    sampling:
      probability: 1.0