eureka:
  instance:
    hostname: discovery
  client:
    service-url:
      defaultZone: http://discovery:8080/eureka
server:
  port: 8080
spring:
  application:
    name: users

management:
  tracing:
    sampling:
      probability: 1.0